version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_base
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: mi_contraseña
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ingesta:
    build: ./ingesta02   # tu Dockerfile de Python está en ./ingesta02
    container_name: ingesta-app
    depends_on:
      - mysql
    volumes:
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
    environment:
      MYSQL_HOST: mysql        # <-- nombre del servicio
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: mi_contraseña
      MYSQL_DATABASE: mi_base
      MYSQL_PORT: 3306

volumes:
  mysql_data:
